import { createContext, useContext, useState, useCallback, type ReactNode } from 'react';

// ============ Extensible language registry ============
// To add a new language: add its code to `LANGUAGES`, add a `LANG_LABELS` entry,
// add a dictionary below, and register it in `dictionaries`.
export const LANGUAGES = ['pl', 'en'] as const;
export type Lang = (typeof LANGUAGES)[number];

export const LANG_LABELS: Record<Lang, { native: string; short: string }> = {
  pl: { native: 'Polski', short: 'PL' },
  en: { native: 'English', short: 'EN' },
};

export interface LangState {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const LangContext = createContext<LangState | undefined>(undefined);

const STORAGE_KEY = 'app-lang';

function getInitialLang(): Lang {
  if (typeof window === 'undefined') return 'pl';
  const stored = window.localStorage.getItem(STORAGE_KEY);
  if (stored && (LANGUAGES as readonly string[]).includes(stored)) return stored as Lang;
  return 'pl';
}

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(getInitialLang);

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    if (typeof window !== 'undefined') window.localStorage.setItem(STORAGE_KEY, l);
  }, []);

  const t = useCallback(
    (key: string, vars?: Record<string, string | number>): string => {
      const dict = dictionaries[lang] ?? dictionaries.pl;
      let val = dict[key] ?? dictionaries.pl[key] ?? key;
      if (vars) {
        for (const [k, v] of Object.entries(vars)) {
          val = val.replace(new RegExp(`\\{${k}\\}`, 'g'), String(v));
        }
      }
      return val;
    },
    [lang]
  );

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang(): LangState {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used within LangProvider');
  return ctx;
}

// ============ Dictionaries ============

type Dict = Record<string, string>;

const pl: Dict = {
  // Generic
  'common.save': 'Zapisz',
  'common.cancel': 'Anuluj',
  'common.delete': 'Usuń',
  'common.edit': 'Edytuj',
  'common.add': 'Dodaj',
  'common.search': 'Szukaj',
  'common.loading': 'Wczytywanie…',
  'common.confirm': 'Potwierdź',
  'common.close': 'Zamknij',
  'common.yes': 'Tak',
  'common.no': 'Nie',
  'common.all': 'Wszystko',
  'common.none': 'Brak',
  'common.actions': 'Akcje',
  'common.name': 'Nazwa',
  'common.description': 'Opis',
  'common.status': 'Status',
  'common.type': 'Typ',
  'common.date': 'Data',
  'common.back': 'Wstecz',
  'common.required': 'Wymagane',
  'common.optional': 'Opcjonalne',
  'common.created': 'Utworzono',
  'common.updated': 'Zaktualizowano',
  'common.deleted': 'Usunięto',
  'common.open': 'Otwórz',
  'common.noFile': 'Brak pliku',
  'common.dash': '—',
  'common.select': '— wybierz —',

  // Auth
  'auth.signIn': 'Zaloguj się',
  'auth.signUp': 'Załóż konto',
  'auth.email': 'E-mail',
  'auth.password': 'Hasło',
  'auth.displayName': 'Nazwa wyświetlana',
  'auth.signInBtn': 'Zaloguj',
  'auth.signUpBtn': 'Zarejestruj',
  'auth.noAccount': 'Nie masz konta?',
  'auth.haveAccount': 'Masz już konto?',
  'auth.welcome': 'Witaj w systemie zarządzania strukturą organizacyjną',
  'auth.subtitle': 'Zaloguj się, aby zarządzać działami, pracownikami i procesami',
  'auth.selectRole': 'Wybierz rolę',
  'auth.roleAdmin': 'Administrator',
  'auth.roleHr': 'HR',
  'auth.roleEmployee': 'Pracownik',
  'auth.signOut': 'Wyloguj',
  'auth.cancelSignOut': 'Anuluj i wyloguj',
  'auth.loadingSession': 'Wczytywanie sesji…',
  'auth.initProfile': 'Inicjalizacja profilu…',
  'auth.createAccount': 'Utwórz konto',
  'auth.enterCredentials': 'Wprowadź dane, aby przejść do panelu.',
  'auth.chooseRoleFill': 'Wybierz rolę i wypełnij formularz.',
  'auth.fullName': 'Imię i nazwisko',
  'auth.fullNamePh': 'np. Jan Kowalski',
  'auth.processing': 'Przetwarzanie…',
  'auth.demoAccounts': 'Konta demo (kliknij, aby wypełnić)',
  'auth.demoPassword': 'Hasło dla wszystkich kont demo:',
  'auth.locked': 'Zablokowane',
  'auth.errInvalid': 'Nieprawidłowy email lub hasło.',
  'auth.errNotConfirmed': 'Konto nie zostało potwierdzone.',
  'auth.errExists': 'Konto z tym adresem już istnieje. Zaloguj się.',
  'auth.errPasswordShort': 'Hasło musi mieć co najmniej 6 znaków.',
  'auth.errAdminSelf': 'Rola Administrator nie jest dostępna przy samodzielnej rejestracji. Wybierz Pracownik lub HR, a administrator nada rolę po zalogowaniu.',

  // Nav sections
  'nav.main': 'Główne',
  'nav.organization': 'Organizacja',
  'nav.operations': 'Operacje',
  'nav.system': 'System',

  // Nav items
  'nav.dashboard': 'Dashboard',
  'nav.company': 'Firma',
  'nav.structure': 'Struktura organizacyjna',
  'nav.board': 'Zarząd',
  'nav.departments': 'Działy',
  'nav.organigram': 'Organigram',
  'nav.employees': 'Pracownicy',
  'nav.positions': 'Stanowiska',
  'nav.processes': 'Procesy',
  'nav.performance': 'Oceny pracownicze',
  'nav.documents': 'Dokumenty',
  'nav.reports': 'Raporty',
  'nav.admin': 'Administracja',

  // Page meta
  'page.dashboard.title': 'Dashboard',
  'page.dashboard.subtitle': 'Przegląd struktury organizacyjnej',
  'page.company.title': 'Firma',
  'page.company.subtitle': 'Dane firmy i lokalizacje',
  'page.structure.title': 'Struktura organizacyjna',
  'page.structure.subtitle': 'Zarządzaj hierarchią działów i zespołów',
  'page.board.title': 'Zarząd',
  'page.board.subtitle': 'Członkowie zarządu',
  'page.departments.title': 'Działy',
  'page.departments.subtitle': 'Hierarchia jednostek organizacyjnych',
  'page.organigram.title': 'Organigram',
  'page.organigram.subtitle': 'Wizualny schemat organizacyjny',
  'page.employees.title': 'Pracownicy',
  'page.employees.subtitle': 'Katalog pracowników',
  'page.positions.title': 'Stanowiska',
  'page.positions.subtitle': 'Role i zakresy obowiązków',
  'page.processes.title': 'Procesy',
  'page.processes.subtitle': 'Kluczowe procesy biznesowe',
  'page.performance.title': 'Oceny pracownicze',
  'page.performance.subtitle': 'Cele, OKR i oceny okresowe',
  'page.documents.title': 'Dokumenty',
  'page.documents.subtitle': 'Regulaminy, procedury i polityki',
  'page.reports.title': 'Raporty',
  'page.reports.subtitle': 'Statystyki i analityka organizacyjna',
  'page.admin.title': 'Administracja',
  'page.admin.subtitle': 'Role, uprawnienia i historia zmian',

  // Role labels
  'role.admin': 'Administrator',
  'role.hr': 'HR',
  'role.employee': 'Pracownik',

  // Footer
  'footer.tagline': 'System zarządzania strukturą organizacyjną',

  // Empty / error states
  'error.noData.title': 'Brak danych do wyświetlenia',
  'error.noData.desc': 'Twoje konto nie ma uprawnień do odczytu danych lub baza jest pusta. Skontaktuj się z administratorem.',
  'error.generic': 'Wystąpił błąd',
  'error.deleteFailed': 'Nie udało się usunąć',

  // Badges — employee status
  'badge.status.active': 'Aktywny',
  'badge.status.on_leave': 'Na urlopie',
  'badge.status.terminated': 'Zatrzymany',

  // Badges — priority
  'badge.priority.critical': 'Krytyczny',
  'badge.priority.high': 'Wysoki',
  'badge.priority.medium': 'Średni',
  'badge.priority.low': 'Niski',

  // Badges — process category
  'badge.category.Operational': 'Operacyjny',
  'badge.category.Strategic': 'Strategiczny',
  'badge.category.Support': 'Wspierający',
  'badge.category.Financial': 'Finansowy',

  // Badges — document type
  'badge.docType.regulation': 'Regulamin',
  'badge.docType.procedure': 'Procedura',
  'badge.docType.policy': 'Polityka',
  'badge.docType.instruction': 'Instrukcja',

  // Badges — document status
  'badge.docStatus.active': 'Obowiązujący',
  'badge.docStatus.draft': 'Roboczy',
  'badge.docStatus.archived': 'Zarchiwizowany',

  // Badges — substitution status
  'badge.subst.active': 'Aktywne',
  'badge.subst.scheduled': 'Zaplanowane',
  'badge.subst.ended': 'Zakończone',

  // Badges — misc
  'badge.board': 'Zarząd',
  'badge.boardMember': 'Członek Zarządu',
  'badge.vacant': 'Wakat',
  'badge.filled': 'Obsadzone',
  'badge.HQ': 'Centrala',
  'badge.version': 'Wersja {v}',

  // Structure / Organigram page
  'structure.creator.title': 'Kreator struktury organizacyjnej',
  'structure.creator.desc.write': 'Przeciągnij jednostki, aby zmienić hierarchię. Dodawaj działy, zespoły i kierowników.',
  'structure.creator.desc.readonly': 'Wizualny schemat struktury organizacyjnej',
  'structure.exportPdf': 'Eksport PDF',
  'structure.newUnit': 'Nowa jednostka',
  'structure.expandAll': 'Rozwiń wszystkie',
  'structure.collapseAll': 'Zwiń wszystkie',
  'structure.viewTree': 'Drzewo',
  'structure.viewRadial': 'Szczegółowe',
  'structure.viewList': 'Lista',
  'structure.viewHistory': 'Historia zmian',
  'structure.empty': 'Brak jednostek. Dodaj pierwszą jednostkę organizacyjną.',
  'structure.employees.short': 'prac.',
  'structure.subdepartments': 'poddziałów',
  'structure.manager': 'Kierownik',
  'structure.addSub': 'Dodaj poddział',
  'structure.changeManager': 'Zmień kierownika',
  'structure.changeSupervisor': 'Zmień przełożonego',
  'structure.dragHint': 'Przeciągnij, aby przenieść',
  'structure.noUnits': 'Brak jednostek. Dodaj pierwszą jednostkę organizacyjną.',

  // Structure history
  'structure.history.title': 'Historia zmian struktury',
  'structure.history.desc': 'Rejestr wszystkich zmian w hierarchii organizacyjnej',
  'structure.history.empty': 'Brak zarejestrowanych zmian struktury.',
  'structure.history.action.create': 'Utworzenie',
  'structure.history.action.update': 'Aktualizacja',
  'structure.history.action.delete': 'Usunięcie',
  'structure.history.by': 'przez',
  'structure.history.entity.department': 'Dział',
  'structure.history.entity.employee': 'Pracownik',
  'structure.history.entity.position': 'Stanowisko',

  // Department form modal
  'deptForm.title.new': 'Nowa jednostka organizacyjna',
  'deptForm.title.edit': 'Edytuj jednostkę organizacyjną',
  'deptForm.name': 'Nazwa',
  'deptForm.name.ph': 'np. Produkcja',
  'deptForm.code': 'Kod',
  'deptForm.code.ph': 'np. PROD',
  'deptForm.icon': 'Ikona',
  'deptForm.parent': 'Jednostka nadrzędna',
  'deptForm.parent.none': '— (poziom główny)',
  'deptForm.manager': 'Kierownik',
  'deptForm.description': 'Opis',
  'deptForm.saveNew': 'Dodaj',
  'deptForm.saveEdit': 'Zapisz zmiany',
  'deptForm.saving': 'Zapisywanie…',
  'deptForm.err.name': 'Nazwa działu jest wymagana.',

  // Manager picker
  'managerPicker.title': 'Kierownik działu',
  'managerPicker.none': '— brak kierownika —',

  // Supervisor picker
  'supervisorPicker.title': 'Przełożony dla {name}',
  'supervisorPicker.none': '— brak —',

  // Confirm delete
  'confirm.deleteUnit.title': 'Usunąć jednostkę?',
  'confirm.deleteUnit.msg': 'Czy na pewno chcesz usunąć "{name}"? Podległe jednostki zostaną przeniesione na wyższy poziom.',
  'confirm.delete.title': 'Usunąć?',
  'confirm.deleteEmployee.title': 'Usunąć pracownika?',
  'confirm.deleteEmployee.msg': 'Czy na pewno chcesz usunąć {name}? Tej operacji nie można cofnąć.',
  'confirm.deletePosition.title': 'Usunąć stanowisko?',
  'confirm.deletePosition.msg': 'Czy na pewno chcesz usunąć stanowisko „{name}"? Tej operacji nie można cofnąć.',
  'confirm.deleteProcess.title': 'Usunąć proces?',
  'confirm.deleteProcess.msg': 'Czy na pewno chcesz usunąć proces "{name}"? Tej operacji nie można cofnąć.',
  'confirm.deleteDocument.title': 'Usunąć dokument?',
  'confirm.deleteDocument.msg': 'Czy na pewno chcesz usunąć "{name}"? Wszystkie wersje zostaną trwale usunięte.',
  'confirm.deleteGoal.title': 'Usunąć cel?',
  'confirm.deleteReview.title': 'Usunąć ocenę?',
  'confirm.deletePerf.msg': 'Czy na pewno chcesz usunąć "{name}"? Tej operacji nie można cofnąć.',

  // Drag error
  'drag.descendantErr': 'Nie można przenieść działu do jego własnego poddziału.',

  // Employees
  'employee.loadingProfile': 'Wczytywanie profilu…',
  'employee.supervisor': 'Przełożony: {name}',
  'employee.hired': 'Zatrudniony: {tenure}',
  'employee.boardMember': 'Członek Zarządu',
  'employee.email': 'Email',
  'employee.phone': 'Telefon',
  'employee.department': 'Dział',
  'employee.location': 'Lokalizacja',
  'employee.hiredFrom': 'Zatrudniony od',
  'employee.tenure': 'Staż',
  'employee.directReports': 'Podwładni ({count})',
  'employee.noReports': 'Brak bezpośrednich podwładnych.',
  'employee.competencies': 'Kompetencje',
  'employee.specializations': 'Specjalizacje',
  'employee.responsibilities': 'Zakres obowiązków',
  'employee.decisionRights': 'Uprawnienia decyzyjne',
  'employee.hrData': 'Dane HR',
  'employee.salaryMonthly': 'Wynagrodzenie miesięczne brutto',
  'employee.leaveUsed': 'Wykorzystany urlop',
  'employee.sickDays': 'Zwolnienie lekarskie (L4)',
  'employee.salaryRange': 'Widełki na stanowisku',
  'employee.days': 'dni',

  // Employee form
  'empForm.title.new': 'Nowy pracownik',
  'empForm.title.edit': 'Edytuj pracownika',
  'empForm.subtitle.new': 'Dodaj nowego pracownika do katalogu',
  'empForm.firstName': 'Imię *',
  'empForm.lastName': 'Nazwisko *',
  'empForm.email': 'Email',
  'empForm.phone': 'Telefon',
  'empForm.position': 'Stanowisko',
  'empForm.department': 'Dział',
  'empForm.manager': 'Przełożony',
  'empForm.location': 'Lokalizacja',
  'empForm.hireDate': 'Data zatrudnienia',
  'empForm.status': 'Status',
  'empForm.avatarUrl': 'URL awatara',
  'empForm.competencies': 'Kompetencje (oddzielone przecinkami)',
  'empForm.competenciesPh': 'np. Zarządzanie, Excel, Prawo',
  'empForm.specializations': 'Specjalizacje (oddzielone przecinkami)',
  'empForm.specializationsPh': 'np. Audyt, Budżetowanie',
  'empForm.isBoardMember': 'Członek zarządu',
  'empForm.hrData': 'Dane HR',
  'empForm.salary': 'Miesięczne wynagrodzenie brutto (PLN)',
  'empForm.leaveDays': 'Wykorzystany urlop (dni)',
  'empForm.sickDays': 'Dni na zwolnieniu lekarskim (L4)',
  'empForm.err.nameRequired': 'Imię i nazwisko są wymagane.',
  'empForm.saveNew': 'Dodaj pracownika',
  'empForm.saveEdit': 'Zapisz zmiany',
  'empForm.saving': 'Zapisywanie…',

  // Employees page
  'empPage.searchPh': 'Szukaj pracownika, stanowiska, kompetencji…',
  'empPage.addEmployee': 'Dodaj pracownika',
  'empPage.filterDept': 'Dział',
  'empPage.filterDeptAll': 'Wszystkie działy',
  'empPage.filterLocation': 'Lokalizacja',
  'empPage.filterLocationAll': 'Wszystkie lokalizacje',
  'empPage.filterLevel': 'Poziom stanowiska',
  'empPage.filterLevelAll': 'Wszystkie poziomy',
  'empPage.filterCompetency': 'Kompetencja',
  'empPage.filterCompetencyAll': 'Wszystkie kompetencje',
  'empPage.results': 'Znaleziono {found} z {total} pracowników',
  'empPage.filtersActive': '· {count} filtr(ów) aktywnych',
  'empPage.clearFilters': 'Wyczyść filtry',
  'empPage.empty.title': 'Brak wyników',
  'empPage.empty.desc': 'Nie znaleziono pracowników spełniających kryteria. Zmień filtry lub wyszukiwanie.',
  'empPage.colEmployee': 'Pracownik',
  'empPage.colPosition': 'Stanowisko',
  'empPage.colDepartment': 'Dział',
  'empPage.colLocation': 'Lokalizacja',
  'empPage.colStatus': 'Status',

  // Company page
  'company.noData': 'Brak danych firmy.',
  'company.founded': 'Założono {year}',
  'company.employees': '{count} pracowników',
  'company.email': 'Email',
  'company.phone': 'Telefon',
  'company.website': 'Strona WWW',
  'company.address': 'Adres centrali',
  'company.locations': 'Lokalizacje oddziałów',
  'company.locationsCount': '{count} lokalizacji',
  'company.board': 'Zarząd',
  'company.boardMembers': '{count} członków',
  'company.statEmployees': 'Pracowników',
  'company.statDepartments': 'Jednostek org.',
  'company.statLocations': 'Lokalizacji',
  'company.statYears': 'Lat działalności',

  // Board page
  'board.title': 'Zarząd',
  'board.subtitle': 'Najwyższy organ kierowniczy — {count} członków',
  'board.since': 'Od {date}',
  'board.tenure': '{tenure}',
  'board.responsibilities': 'Kluczowe odpowiedzialności',
  'board.decisionRights': 'Uprawnienia decyzyjne',

  // Departments page
  'deptPage.title': 'Struktura organizacyjna',
  'deptPage.subtitle': '{total} jednostek w {pions} pionach',
  'deptPage.filterPh': 'Filtruj działy…',
  'deptPage.manager': 'Kierownik: {name}',
  'deptPage.empty.title': 'Brak działów',
  'deptPage.empty.desc': 'Nie znaleziono jednostek organizacyjnych.',
  'deptPage.expand': 'Rozwiń',
  'deptPage.collapse': 'Zwiń',

  // Positions page
  'posPage.count': 'Stanowisk',
  'posPage.vacant': 'Wakatów',
  'posPage.filled': 'Obsadzonych',
  'posPage.levels': 'Poziomów',
  'posPage.searchPh': 'Szukaj stanowiska…',
  'posPage.addPosition': 'Dodaj stanowisko',
  'posPage.filterDeptAll': 'Wszystkie działy',
  'posPage.filterLevelAll': 'Wszystkie poziomy',
  'posPage.filterStatusAll': 'Wszystkie statusy',
  'posPage.filterFilled': 'Obsadzone',
  'posPage.filterVacant': 'Wakaty',
  'posPage.empty.title': 'Brak stanowisk',
  'posPage.empty.desc': 'Nie znaleziono stanowisk spełniających kryteria.',
  'posPage.heldBy': 'Obsadzone przez: {name}',
  'posPage.salaryRange': 'Widełki wynagrodzenia',
  'posPage.responsibilities': 'Zakres obowiązków',
  'posPage.decisionRights': 'Uprawnienia decyzyjne',
  'posPage.requirements': 'Wymagania',

  // Position form
  'posForm.title.new': 'Nowe stanowisko',
  'posForm.title.edit': 'Edytuj stanowisko',
  'posForm.title': 'Nazwa stanowiska *',
  'posForm.department': 'Dział',
  'posForm.level': 'Poziom',
  'posForm.minSalary': 'Płaca min (PLN)',
  'posForm.maxSalary': 'Płaca max (PLN)',
  'posForm.description': 'Opis',
  'posForm.responsibilities': 'Zakres obowiązków (po jednym w wierszu)',
  'posForm.responsibilitiesPh': 'Zarządzanie zespołem\nPlanowanie budżetu',
  'posForm.decisionRights': 'Uprawnienia decyzyjne',
  'posForm.requirements': 'Wymagania (oddzielone przecinkami)',
  'posForm.requirementsPh': 'np. Excel, MS Office, Prawo pracy',
  'posForm.isVacant': 'Wakat (stanowisko nieobsadzone)',
  'posForm.err.titleRequired': 'Nazwa stanowiska jest wymagana.',
  'posForm.saveNew': 'Dodaj stanowisko',
  'posForm.saveEdit': 'Zapisz zmiany',
  'posForm.saving': 'Zapisywanie…',

  // Processes page
  'procPage.searchPh': 'Szukaj procesu…',
  'procPage.addProcess': 'Dodaj proces',
  'procPage.filterCategoryAll': 'Wszystkie kategorie',
  'procPage.filterPriorityAll': 'Wszystkie priorytety',
  'procPage.empty.title': 'Brak procesów',
  'procPage.empty.desc': 'Nie znaleziono procesów spełniających kryteria.',
  'procPage.owner': 'Właściciel procesu',
  'procPage.relatedDepts': 'Powiązane działy',

  // Process form
  'procForm.title.new': 'Nowy proces',
  'procForm.title.edit': 'Edytuj proces',
  'procForm.name': 'Nazwa procesu *',
  'procForm.description': 'Opis',
  'procForm.owner': 'Właściciel procesu',
  'procForm.category': 'Kategoria',
  'procForm.priority': 'Priorytet',
  'procForm.status': 'Status',
  'procForm.err.nameRequired': 'Nazwa procesu jest wymagana.',
  'procForm.saveNew': 'Dodaj proces',
  'procForm.saveEdit': 'Zapisz zmiany',
  'procForm.saving': 'Zapisywanie…',

  // Documents page
  'docPage.searchPh': 'Szukaj dokumentu…',
  'docPage.addDocument': 'Dodaj dokument',
  'docPage.filterTypeAll': 'Wszystkie typy',
  'docPage.filterStatusAll': 'Wszystkie statusy',
  'docPage.filterDeptAll': 'Wszystkie działy',
  'docPage.results': 'Znaleziono {found} z {total} dokumentów',
  'docPage.empty.title': 'Brak dokumentów',
  'docPage.empty.desc': 'Nie znaleziono dokumentów spełniających kryteria.',
  'docPage.groupCount': '{count} dokumentów',
  'docPage.companyGeneral': 'Firma',
  'docPage.noFile': 'Brak pliku',

  // Document type groups
  'docGroup.regulation': 'Regulaminy',
  'docGroup.procedure': 'Procedury',
  'docGroup.policy': 'Polityki firmowe',
  'docGroup.instruction': 'Instrukcje',

  // Document form
  'docForm.title.new': 'Nowy dokument',
  'docForm.title.edit': 'Edytuj dokument',
  'docForm.title': 'Tytuł *',
  'docForm.description': 'Opis',
  'docForm.type': 'Typ',
  'docForm.status': 'Status',
  'docForm.department': 'Dział',
  'docForm.departmentGeneral': 'Firma (ogólny)',
  'docForm.version': 'Wersja',
  'docForm.effectiveDate': 'Data wejścia w życie',
  'docForm.fileUrl': 'URL pliku',
  'docForm.err.titleRequired': 'Tytuł dokumentu jest wymagany.',
  'docForm.saveNew': 'Dodaj dokument',
  'docForm.saveEdit': 'Zapisz zmiany',
  'docForm.saving': 'Zapisywanie…',

  // Document detail
  'docDetail.version': 'Wersja {v}',
  'docDetail.department': 'Dział',
  'docDetail.effectiveDate': 'Data wejścia w życie',
  'docDetail.file': 'Plik',
  'docDetail.added': 'Dodano',
  'docDetail.versionHistory': 'Historia wersji ({count})',
  'docDetail.noVersions': 'Brak wcześniejszych wersji. Wersje są archiwizowane automatycznie przy każdej edycji dokumentu.',
  'docDetail.archivedAt': 'Archiwizacja: {date}',
  'docDetail.archivedBy': 'Przez: {name}',
  'docDetail.effectiveDateShort': 'Data wejścia: {date}',
  'docDetail.restore': 'Przywróć',
  'docDetail.restoreTitle': 'Przywróć tę wersję',
  'docDetail.restoreFailed': 'Nie udało się przywrócić wersji',
  'docDetail.general': 'Firma (ogólny)',

  // Performance page
  'perfPage.searchPh': 'Szukaj…',
  'perfPage.filterEmployeeAll': 'Wszyscy pracownicy',
  'perfPage.addGoal': 'Dodaj cel',
  'perfPage.addReview': 'Dodaj ocenę',
  'perfPage.tabGoals': 'Cele / OKR',
  'perfPage.tabReviews': 'Oceny okresowe',
  'perfPage.tabHistory': 'Historia',
  'perfPage.emptyGoals.title': 'Brak celów',
  'perfPage.emptyGoals.desc': 'Nie znaleziono celów spełniających kryteria.',
  'perfPage.emptyReviews.title': 'Brak ocen',
  'perfPage.emptyReviews.desc': 'Nie znaleziono ocen spełniających kryteria.',
  'perfPage.emptyHistory.title': 'Wybierz pracownika',
  'perfPage.emptyHistory.desc': 'Wybierz pracownika, aby zobaczyć historię jego celów i ocen.',
  'perfPage.goalType.okr': 'OKR',
  'perfPage.goalType.quarter': 'Kwartalny',
  'perfPage.goalStatus.completed': 'Zrealizowany',
  'perfPage.goalStatus.overdue': 'Przeterminowany',
  'perfPage.goalStatus.active': 'Aktywny',
  'perfPage.progress': 'Postęp',
  'perfPage.dueDate': 'Termin: {date}',
  'perfPage.reviewType.periodic': 'Okresowa',
  'perfPage.reviewType.okr': 'OKR',
  'perfPage.reviewType.annual': 'Roczna',
  'perfPage.reviewStatus.acknowledged': 'Potwierdzona',
  'perfPage.reviewStatus.submitted': 'Przekazana',
  'perfPage.reviewStatus.draft': 'Robocza',
  'perfPage.managerRating': 'Ocena managera',
  'perfPage.selfRating': 'Samoocena',
  'perfPage.managerFeedback': 'Feedback managera',
  'perfPage.selfAssessment': 'Samoocena',
  'perfPage.historyEmployee': 'Pracownik',
  'perfPage.historyGoals': 'Cele ({count})',
  'perfPage.historyReviews': 'Oceny ({count})',
  'perfPage.noGoals': 'Brak celów.',
  'perfPage.noReviews': 'Brak ocen.',
  'perfPage.review': 'Ocena',

  // Goal form
  'goalForm.title.new': 'Nowy cel / OKR',
  'goalForm.title.edit': 'Edytuj cel',
  'goalForm.employee': 'Pracownik *',
  'goalForm.title': 'Tytuł celu *',
  'goalForm.titlePh': 'np. Zwiększenie sprzedaży o 15%',
  'goalForm.description': 'Opis / Kluczowe rezultaty',
  'goalForm.type': 'Typ',
  'goalForm.typeQuarter': 'Cel kwartalny',
  'goalForm.typeOkr': 'OKR',
  'goalForm.quarter': 'Okres (np. 2026-Q1)',
  'goalForm.targetDate': 'Termin',
  'goalForm.status': 'Status',
  'goalForm.progress': 'Postęp: {value}%',
  'goalForm.err.titleRequired': 'Tytuł celu jest wymagany.',
  'goalForm.err.employeeRequired': 'Wybierz pracownika.',
  'goalForm.saveNew': 'Dodaj cel',
  'goalForm.saveEdit': 'Zapisz zmiany',
  'goalForm.saving': 'Zapisywanie…',

  // Review form
  'reviewForm.title.new': 'Nowa ocena pracownicza',
  'reviewForm.title.edit': 'Edytuj ocenę',
  'reviewForm.employee': 'Pracownik *',
  'reviewForm.period': 'Okres (np. 2026-Q1, 2026-H1)',
  'reviewForm.type': 'Typ oceny',
  'reviewForm.typePeriodic': 'Ocena okresowa',
  'reviewForm.typeOkr': 'Ocena OKR',
  'reviewForm.typeAnnual': 'Ocena roczna',
  'reviewForm.managerRating': 'Ocena managera (1-5)',
  'reviewForm.selfRating': 'Samoocena pracownika (1-5)',
  'reviewForm.managerFeedback': 'Feedback managera',
  'reviewForm.managerFeedbackPh': 'Mocne strony, obszary do rozwoju…',
  'reviewForm.selfAssessment': 'Samoocena pracownika',
  'reviewForm.selfAssessmentPh': 'Refleksja pracownika nad własną pracą…',
  'reviewForm.reviewedBy': 'Oceniający (email)',
  'reviewForm.status': 'Status',
  'reviewForm.err.employeeRequired': 'Wybierz pracownika.',
  'reviewForm.saveNew': 'Dodaj ocenę',
  'reviewForm.saveEdit': 'Zapisz zmiany',
  'reviewForm.saving': 'Zapisywanie…',

  // Reports page
  'reports.employees': 'Pracownicy',
  'reports.departments': 'Działy',
  'reports.positions': 'Stanowiska',
  'reports.vacancies': 'Wakaty',
  'reports.empPerPion': 'Zatrudnienie w pionach',
  'reports.empPerPionSub': 'Liczba pracowników na dyrekcję (z poddziałami)',
  'reports.empPerPionStats': '{emp} prac. · {dept} działów',
  'reports.empPerLocation': 'Pracownicy per lokalizacja',
  'reports.empPerLocationSub': 'Rozkład geograficzny',
  'reports.empCount': '{count} prac.',
  'reports.statusBreakdown': 'Status zatrudnienia',
  'reports.statusActive': 'Aktywni',
  'reports.statusOnLeave': 'Na urlopie',
  'reports.statusTerminated': 'Zatrzymani',
  'reports.positionStructure': 'Struktura stanowisk',
  'reports.positionStructureSub': 'Rozkład poziomów',
  'reports.tenure': 'Staż pracy',
  'reports.tenureSub': 'Rozkład stażu',
  'reports.tenure.lt1': '<1 rok',
  'reports.tenure.1to3': '1-3 lata',
  'reports.tenure.3to5': '3-5 lat',
  'reports.tenure.5to10': '5-10 lat',
  'reports.tenure.10plus': '10+ lat',
  'reports.topCompetencies': 'Najczęstsze kompetencje',
  'reports.topCompetenciesSub': 'Top 8 w firmie',
  'reports.openVacancies': 'Otwarte wakaty',
  'reports.openVacanciesSub': '{count} stanowisk nieobsadzonych',
  'reports.noVacancies': 'Brak otwartych wakatów.',
  'reports.directory': 'Katalog pracowników',
  'reports.directorySub': 'Pełna lista zatrudnionych',
  'reports.unknownLevel': 'Nieokreślony',
  'reports.donutLabel': 'pracowników',

  // Admin page
  'admin.title': 'Administracja i bezpieczeństwo',
  'admin.subtitle': 'Role użytkowników, kontrola dostępu i historia zmian',
  'admin.roles': 'Role',
  'admin.accessRules': 'Reguł dostępu',
  'admin.historyEvents': 'Zdarzeń w historii',
  'admin.rolesTitle': 'Role użytkowników',
  'admin.rolesSub': 'Profile dostępu w systemie',
  'admin.matrixTitle': 'Macierz kontroli dostępu',
  'admin.matrixSub': 'Uprawnienia odczyt/zapis/usuwanie dla każdej roli i zasobu',
  'admin.resource': 'Zasób',
  'admin.permRead': 'Odczyt',
  'admin.permWrite': 'Zapis',
  'admin.permDelete': 'Usuwanie',
  'admin.allowed': 'Dozwolone',
  'admin.denied': 'Zabronione',
  'admin.historyTitle': 'Historia zmian',
  'admin.historySub': 'Audytorium ostatnich modyfikacji w systemie',
  'admin.noHistory': 'Brak zarejestrowanych zmian.',
  'admin.resource.company': 'Firma',
  'admin.resource.employees': 'Pracownicy',
  'admin.resource.documents': 'Dokumenty',
  'admin.resource.processes': 'Procesy',
  'admin.resource.reports': 'Raporty',
  'admin.resource.admin': 'Administracja',

  // PDF export header
  'pdf.organigram': 'Organigram',
  'pdf.generated': 'Wygenerowano',
};

const en: Dict = {
  // Generic
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.add': 'Add',
  'common.search': 'Search',
  'common.loading': 'Loading…',
  'common.confirm': 'Confirm',
  'common.close': 'Close',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.all': 'All',
  'common.none': 'None',
  'common.actions': 'Actions',
  'common.name': 'Name',
  'common.description': 'Description',
  'common.status': 'Status',
  'common.type': 'Type',
  'common.date': 'Date',
  'common.back': 'Back',
  'common.required': 'Required',
  'common.optional': 'Optional',
  'common.created': 'Created',
  'common.updated': 'Updated',
  'common.deleted': 'Deleted',
  'common.open': 'Open',
  'common.noFile': 'No file',
  'common.dash': '—',
  'common.select': '— select —',

  // Auth
  'auth.signIn': 'Sign In',
  'auth.signUp': 'Sign Up',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.displayName': 'Display Name',
  'auth.signInBtn': 'Sign In',
  'auth.signUpBtn': 'Register',
  'auth.noAccount': "Don't have an account?",
  'auth.haveAccount': 'Already have an account?',
  'auth.welcome': 'Welcome to the organizational structure management system',
  'auth.subtitle': 'Sign in to manage departments, employees and processes',
  'auth.selectRole': 'Select role',
  'auth.roleAdmin': 'Administrator',
  'auth.roleHr': 'HR',
  'auth.roleEmployee': 'Employee',
  'auth.signOut': 'Sign Out',
  'auth.cancelSignOut': 'Cancel and sign out',
  'auth.loadingSession': 'Loading session…',
  'auth.initProfile': 'Initializing profile…',
  'auth.createAccount': 'Create account',
  'auth.enterCredentials': 'Enter your credentials to access the panel.',
  'auth.chooseRoleFill': 'Choose a role and fill in the form.',
  'auth.fullName': 'Full name',
  'auth.fullNamePh': 'e.g. John Smith',
  'auth.processing': 'Processing…',
  'auth.demoAccounts': 'Demo accounts (click to fill)',
  'auth.demoPassword': 'Password for all demo accounts:',
  'auth.locked': 'Locked',
  'auth.errInvalid': 'Invalid email or password.',
  'auth.errNotConfirmed': 'Account not confirmed.',
  'auth.errExists': 'An account with this email already exists. Sign in.',
  'auth.errPasswordShort': 'Password must be at least 6 characters.',
  'auth.errAdminSelf': 'Administrator role is not available for self-registration. Choose Employee or HR; an admin will assign the role after login.',

  // Nav sections
  'nav.main': 'Main',
  'nav.organization': 'Organization',
  'nav.operations': 'Operations',
  'nav.system': 'System',

  // Nav items
  'nav.dashboard': 'Dashboard',
  'nav.company': 'Company',
  'nav.structure': 'Org Structure',
  'nav.board': 'Board',
  'nav.departments': 'Departments',
  'nav.organigram': 'Organigram',
  'nav.employees': 'Employees',
  'nav.positions': 'Positions',
  'nav.processes': 'Processes',
  'nav.performance': 'Performance',
  'nav.documents': 'Documents',
  'nav.reports': 'Reports',
  'nav.admin': 'Administration',

  // Page meta
  'page.dashboard.title': 'Dashboard',
  'page.dashboard.subtitle': 'Organizational structure overview',
  'page.company.title': 'Company',
  'page.company.subtitle': 'Company data and locations',
  'page.structure.title': 'Org Structure',
  'page.structure.subtitle': 'Manage department and team hierarchy',
  'page.board.title': 'Board',
  'page.board.subtitle': 'Board members',
  'page.departments.title': 'Departments',
  'page.departments.subtitle': 'Organizational unit hierarchy',
  'page.organigram.title': 'Organigram',
  'page.organigram.subtitle': 'Visual organizational chart',
  'page.employees.title': 'Employees',
  'page.employees.subtitle': 'Employee directory',
  'page.positions.title': 'Positions',
  'page.positions.subtitle': 'Roles and responsibilities',
  'page.processes.title': 'Processes',
  'page.processes.subtitle': 'Key business processes',
  'page.performance.title': 'Performance',
  'page.performance.subtitle': 'Goals, OKRs and periodic reviews',
  'page.documents.title': 'Documents',
  'page.documents.subtitle': 'Regulations, procedures and policies',
  'page.reports.title': 'Reports',
  'page.reports.subtitle': 'Organizational statistics and analytics',
  'page.admin.title': 'Administration',
  'page.admin.subtitle': 'Roles, permissions and change history',

  // Role labels
  'role.admin': 'Administrator',
  'role.hr': 'HR',
  'role.employee': 'Employee',

  // Footer
  'footer.tagline': 'Organizational structure management system',

  // Empty / error states
  'error.noData.title': 'No data to display',
  'error.noData.desc': 'Your account lacks read permissions or the database is empty. Contact your administrator.',
  'error.generic': 'An error occurred',
  'error.deleteFailed': 'Failed to delete',

  // Badges — employee status
  'badge.status.active': 'Active',
  'badge.status.on_leave': 'On leave',
  'badge.status.terminated': 'Terminated',

  // Badges — priority
  'badge.priority.critical': 'Critical',
  'badge.priority.high': 'High',
  'badge.priority.medium': 'Medium',
  'badge.priority.low': 'Low',

  // Badges — process category
  'badge.category.Operational': 'Operational',
  'badge.category.Strategic': 'Strategic',
  'badge.category.Support': 'Support',
  'badge.category.Financial': 'Financial',

  // Badges — document type
  'badge.docType.regulation': 'Regulation',
  'badge.docType.procedure': 'Procedure',
  'badge.docType.policy': 'Policy',
  'badge.docType.instruction': 'Instruction',

  // Badges — document status
  'badge.docStatus.active': 'In effect',
  'badge.docStatus.draft': 'Draft',
  'badge.docStatus.archived': 'Archived',

  // Badges — substitution status
  'badge.subst.active': 'Active',
  'badge.subst.scheduled': 'Scheduled',
  'badge.subst.ended': 'Ended',

  // Badges — misc
  'badge.board': 'Board',
  'badge.boardMember': 'Board Member',
  'badge.vacant': 'Vacant',
  'badge.filled': 'Filled',
  'badge.HQ': 'HQ',
  'badge.version': 'Version {v}',

  // Structure / Organigram page
  'structure.creator.title': 'Org Structure Creator',
  'structure.creator.desc.write': 'Drag units to change hierarchy. Add departments, teams and managers.',
  'structure.creator.desc.readonly': 'Visual organizational structure chart',
  'structure.exportPdf': 'Export PDF',
  'structure.newUnit': 'New Unit',
  'structure.expandAll': 'Expand all',
  'structure.collapseAll': 'Collapse all',
  'structure.viewTree': 'Tree',
  'structure.viewRadial': 'Detail',
  'structure.viewList': 'List',
  'structure.viewHistory': 'Change History',
  'structure.empty': 'No units. Add your first organizational unit.',
  'structure.employees.short': 'emp.',
  'structure.subdepartments': 'sub-units',
  'structure.manager': 'Manager',
  'structure.addSub': 'Add sub-unit',
  'structure.changeManager': 'Change manager',
  'structure.changeSupervisor': 'Change supervisor',
  'structure.dragHint': 'Drag to move',
  'structure.noUnits': 'No units. Add your first organizational unit.',

  // Structure history
  'structure.history.title': 'Structure change history',
  'structure.history.desc': 'Log of all changes to the organizational hierarchy',
  'structure.history.empty': 'No structure changes recorded.',
  'structure.history.action.create': 'Created',
  'structure.history.action.update': 'Updated',
  'structure.history.action.delete': 'Deleted',
  'structure.history.by': 'by',
  'structure.history.entity.department': 'Department',
  'structure.history.entity.employee': 'Employee',
  'structure.history.entity.position': 'Position',

  // Department form modal
  'deptForm.title.new': 'New organizational unit',
  'deptForm.title.edit': 'Edit organizational unit',
  'deptForm.name': 'Name',
  'deptForm.name.ph': 'e.g. Production',
  'deptForm.code': 'Code',
  'deptForm.code.ph': 'e.g. PROD',
  'deptForm.icon': 'Icon',
  'deptForm.parent': 'Parent unit',
  'deptForm.parent.none': '— (top level)',
  'deptForm.manager': 'Manager',
  'deptForm.description': 'Description',
  'deptForm.saveNew': 'Add',
  'deptForm.saveEdit': 'Save changes',
  'deptForm.saving': 'Saving…',
  'deptForm.err.name': 'Department name is required.',

  // Manager picker
  'managerPicker.title': 'Department manager',
  'managerPicker.none': '— no manager —',

  // Supervisor picker
  'supervisorPicker.title': 'Supervisor for {name}',
  'supervisorPicker.none': '— none —',

  // Confirm delete
  'confirm.deleteUnit.title': 'Delete unit?',
  'confirm.deleteUnit.msg': 'Are you sure you want to delete "{name}"? Sub-units will be moved up one level.',
  'confirm.delete.title': 'Delete?',
  'confirm.deleteEmployee.title': 'Delete employee?',
  'confirm.deleteEmployee.msg': 'Are you sure you want to delete {name}? This action cannot be undone.',
  'confirm.deletePosition.title': 'Delete position?',
  'confirm.deletePosition.msg': 'Are you sure you want to delete position "{name}"? This action cannot be undone.',
  'confirm.deleteProcess.title': 'Delete process?',
  'confirm.deleteProcess.msg': 'Are you sure you want to delete process "{name}"? This action cannot be undone.',
  'confirm.deleteDocument.title': 'Delete document?',
  'confirm.deleteDocument.msg': 'Are you sure you want to delete "{name}"? All versions will be permanently deleted.',
  'confirm.deleteGoal.title': 'Delete goal?',
  'confirm.deleteReview.title': 'Delete review?',
  'confirm.deletePerf.msg': 'Are you sure you want to delete "{name}"? This action cannot be undone.',

  // Drag error
  'drag.descendantErr': 'Cannot move a unit into its own sub-unit.',

  // Employees
  'employee.loadingProfile': 'Loading profile…',
  'employee.supervisor': 'Supervisor: {name}',
  'employee.hired': 'Hired: {tenure}',
  'employee.boardMember': 'Board Member',
  'employee.email': 'Email',
  'employee.phone': 'Phone',
  'employee.department': 'Department',
  'employee.location': 'Location',
  'employee.hiredFrom': 'Employed since',
  'employee.tenure': 'Tenure',
  'employee.directReports': 'Direct reports ({count})',
  'employee.noReports': 'No direct reports.',
  'employee.competencies': 'Competencies',
  'employee.specializations': 'Specializations',
  'employee.responsibilities': 'Responsibilities',
  'employee.decisionRights': 'Decision rights',
  'employee.hrData': 'HR data',
  'employee.salaryMonthly': 'Monthly gross salary',
  'employee.leaveUsed': 'Leave used',
  'employee.sickDays': 'Sick leave (L4)',
  'employee.salaryRange': 'Position salary range',
  'employee.days': 'days',

  // Employee form
  'empForm.title.new': 'New employee',
  'empForm.title.edit': 'Edit employee',
  'empForm.subtitle.new': 'Add a new employee to the directory',
  'empForm.firstName': 'First name *',
  'empForm.lastName': 'Last name *',
  'empForm.email': 'Email',
  'empForm.phone': 'Phone',
  'empForm.position': 'Position',
  'empForm.department': 'Department',
  'empForm.manager': 'Supervisor',
  'empForm.location': 'Location',
  'empForm.hireDate': 'Hire date',
  'empForm.status': 'Status',
  'empForm.avatarUrl': 'Avatar URL',
  'empForm.competencies': 'Competencies (comma-separated)',
  'empForm.competenciesPh': 'e.g. Management, Excel, Law',
  'empForm.specializations': 'Specializations (comma-separated)',
  'empForm.specializationsPh': 'e.g. Audit, Budgeting',
  'empForm.isBoardMember': 'Board member',
  'empForm.hrData': 'HR data',
  'empForm.salary': 'Monthly gross salary (PLN)',
  'empForm.leaveDays': 'Leave used (days)',
  'empForm.sickDays': 'Sick leave days (L4)',
  'empForm.err.nameRequired': 'First and last name are required.',
  'empForm.saveNew': 'Add employee',
  'empForm.saveEdit': 'Save changes',
  'empForm.saving': 'Saving…',

  // Employees page
  'empPage.searchPh': 'Search employee, position, competency…',
  'empPage.addEmployee': 'Add employee',
  'empPage.filterDept': 'Department',
  'empPage.filterDeptAll': 'All departments',
  'empPage.filterLocation': 'Location',
  'empPage.filterLocationAll': 'All locations',
  'empPage.filterLevel': 'Position level',
  'empPage.filterLevelAll': 'All levels',
  'empPage.filterCompetency': 'Competency',
  'empPage.filterCompetencyAll': 'All competencies',
  'empPage.results': 'Found {found} of {total} employees',
  'empPage.filtersActive': '· {count} filter(s) active',
  'empPage.clearFilters': 'Clear filters',
  'empPage.empty.title': 'No results',
  'empPage.empty.desc': 'No employees found matching the criteria. Adjust filters or search.',
  'empPage.colEmployee': 'Employee',
  'empPage.colPosition': 'Position',
  'empPage.colDepartment': 'Department',
  'empPage.colLocation': 'Location',
  'empPage.colStatus': 'Status',

  // Company page
  'company.noData': 'No company data.',
  'company.founded': 'Founded {year}',
  'company.employees': '{count} employees',
  'company.email': 'Email',
  'company.phone': 'Phone',
  'company.website': 'Website',
  'company.address': 'HQ address',
  'company.locations': 'Office locations',
  'company.locationsCount': '{count} locations',
  'company.board': 'Board',
  'company.boardMembers': '{count} members',
  'company.statEmployees': 'Employees',
  'company.statDepartments': 'Org units',
  'company.statLocations': 'Locations',
  'company.statYears': 'Years in business',

  // Board page
  'board.title': 'Board',
  'board.subtitle': 'Highest governing body — {count} members',
  'board.since': 'Since {date}',
  'board.tenure': '{tenure}',
  'board.responsibilities': 'Key responsibilities',
  'board.decisionRights': 'Decision rights',

  // Departments page
  'deptPage.title': 'Org Structure',
  'deptPage.subtitle': '{total} units in {pions} divisions',
  'deptPage.filterPh': 'Filter departments…',
  'deptPage.manager': 'Manager: {name}',
  'deptPage.empty.title': 'No departments',
  'deptPage.empty.desc': 'No organizational units found.',
  'deptPage.expand': 'Expand',
  'deptPage.collapse': 'Collapse',

  // Positions page
  'posPage.count': 'Positions',
  'posPage.vacant': 'Vacancies',
  'posPage.filled': 'Filled',
  'posPage.levels': 'Levels',
  'posPage.searchPh': 'Search position…',
  'posPage.addPosition': 'Add position',
  'posPage.filterDeptAll': 'All departments',
  'posPage.filterLevelAll': 'All levels',
  'posPage.filterStatusAll': 'All statuses',
  'posPage.filterFilled': 'Filled',
  'posPage.filterVacant': 'Vacancies',
  'posPage.empty.title': 'No positions',
  'posPage.empty.desc': 'No positions found matching the criteria.',
  'posPage.heldBy': 'Held by: {name}',
  'posPage.salaryRange': 'Salary range',
  'posPage.responsibilities': 'Responsibilities',
  'posPage.decisionRights': 'Decision rights',
  'posPage.requirements': 'Requirements',

  // Position form
  'posForm.title.new': 'New position',
  'posForm.title.edit': 'Edit position',
  'posForm.title': 'Position title *',
  'posForm.department': 'Department',
  'posForm.level': 'Level',
  'posForm.minSalary': 'Min salary (PLN)',
  'posForm.maxSalary': 'Max salary (PLN)',
  'posForm.description': 'Description',
  'posForm.responsibilities': 'Responsibilities (one per line)',
  'posForm.responsibilitiesPh': 'Team management\nBudget planning',
  'posForm.decisionRights': 'Decision rights',
  'posForm.requirements': 'Requirements (comma-separated)',
  'posForm.requirementsPh': 'e.g. Excel, MS Office, Labor law',
  'posForm.isVacant': 'Vacant (unfilled position)',
  'posForm.err.titleRequired': 'Position title is required.',
  'posForm.saveNew': 'Add position',
  'posForm.saveEdit': 'Save changes',
  'posForm.saving': 'Saving…',

  // Processes page
  'procPage.searchPh': 'Search process…',
  'procPage.addProcess': 'Add process',
  'procPage.filterCategoryAll': 'All categories',
  'procPage.filterPriorityAll': 'All priorities',
  'procPage.empty.title': 'No processes',
  'procPage.empty.desc': 'No processes found matching the criteria.',
  'procPage.owner': 'Process owner',
  'procPage.relatedDepts': 'Related departments',

  // Process form
  'procForm.title.new': 'New process',
  'procForm.title.edit': 'Edit process',
  'procForm.name': 'Process name *',
  'procForm.description': 'Description',
  'procForm.owner': 'Process owner',
  'procForm.category': 'Category',
  'procForm.priority': 'Priority',
  'procForm.status': 'Status',
  'procForm.err.nameRequired': 'Process name is required.',
  'procForm.saveNew': 'Add process',
  'procForm.saveEdit': 'Save changes',
  'procForm.saving': 'Saving…',

  // Documents page
  'docPage.searchPh': 'Search document…',
  'docPage.addDocument': 'Add document',
  'docPage.filterTypeAll': 'All types',
  'docPage.filterStatusAll': 'All statuses',
  'docPage.filterDeptAll': 'All departments',
  'docPage.results': 'Found {found} of {total} documents',
  'docPage.empty.title': 'No documents',
  'docPage.empty.desc': 'No documents found matching the criteria.',
  'docPage.groupCount': '{count} documents',
  'docPage.companyGeneral': 'Company',
  'docPage.noFile': 'No file',

  // Document type groups
  'docGroup.regulation': 'Regulations',
  'docGroup.procedure': 'Procedures',
  'docGroup.policy': 'Company policies',
  'docGroup.instruction': 'Instructions',

  // Document form
  'docForm.title.new': 'New document',
  'docForm.title.edit': 'Edit document',
  'docForm.title': 'Title *',
  'docForm.description': 'Description',
  'docForm.type': 'Type',
  'docForm.status': 'Status',
  'docForm.department': 'Department',
  'docForm.departmentGeneral': 'Company (general)',
  'docForm.version': 'Version',
  'docForm.effectiveDate': 'Effective date',
  'docForm.fileUrl': 'File URL',
  'docForm.err.titleRequired': 'Document title is required.',
  'docForm.saveNew': 'Add document',
  'docForm.saveEdit': 'Save changes',
  'docForm.saving': 'Saving…',

  // Document detail
  'docDetail.version': 'Version {v}',
  'docDetail.department': 'Department',
  'docDetail.effectiveDate': 'Effective date',
  'docDetail.file': 'File',
  'docDetail.added': 'Added',
  'docDetail.versionHistory': 'Version history ({count})',
  'docDetail.noVersions': 'No previous versions. Versions are archived automatically on each document edit.',
  'docDetail.archivedAt': 'Archived: {date}',
  'docDetail.archivedBy': 'By: {name}',
  'docDetail.effectiveDateShort': 'Effective: {date}',
  'docDetail.restore': 'Restore',
  'docDetail.restoreTitle': 'Restore this version',
  'docDetail.restoreFailed': 'Failed to restore version',
  'docDetail.general': 'Company (general)',

  // Performance page
  'perfPage.searchPh': 'Search…',
  'perfPage.filterEmployeeAll': 'All employees',
  'perfPage.addGoal': 'Add goal',
  'perfPage.addReview': 'Add review',
  'perfPage.tabGoals': 'Goals / OKR',
  'perfPage.tabReviews': 'Periodic reviews',
  'perfPage.tabHistory': 'History',
  'perfPage.emptyGoals.title': 'No goals',
  'perfPage.emptyGoals.desc': 'No goals found matching the criteria.',
  'perfPage.emptyReviews.title': 'No reviews',
  'perfPage.emptyReviews.desc': 'No reviews found matching the criteria.',
  'perfPage.emptyHistory.title': 'Select employee',
  'perfPage.emptyHistory.desc': 'Select an employee to view their goal and review history.',
  'perfPage.goalType.okr': 'OKR',
  'perfPage.goalType.quarter': 'Quarterly',
  'perfPage.goalStatus.completed': 'Completed',
  'perfPage.goalStatus.overdue': 'Overdue',
  'perfPage.goalStatus.active': 'Active',
  'perfPage.progress': 'Progress',
  'perfPage.dueDate': 'Due: {date}',
  'perfPage.reviewType.periodic': 'Periodic',
  'perfPage.reviewType.okr': 'OKR',
  'perfPage.reviewType.annual': 'Annual',
  'perfPage.reviewStatus.acknowledged': 'Acknowledged',
  'perfPage.reviewStatus.submitted': 'Submitted',
  'perfPage.reviewStatus.draft': 'Draft',
  'perfPage.managerRating': 'Manager rating',
  'perfPage.selfRating': 'Self-assessment',
  'perfPage.managerFeedback': 'Manager feedback',
  'perfPage.selfAssessment': 'Self-assessment',
  'perfPage.historyEmployee': 'Employee',
  'perfPage.historyGoals': 'Goals ({count})',
  'perfPage.historyReviews': 'Reviews ({count})',
  'perfPage.noGoals': 'No goals.',
  'perfPage.noReviews': 'No reviews.',
  'perfPage.review': 'Review',

  // Goal form
  'goalForm.title.new': 'New goal / OKR',
  'goalForm.title.edit': 'Edit goal',
  'goalForm.employee': 'Employee *',
  'goalForm.title': 'Goal title *',
  'goalForm.titlePh': 'e.g. Increase sales by 15%',
  'goalForm.description': 'Description / Key results',
  'goalForm.type': 'Type',
  'goalForm.typeQuarter': 'Quarterly goal',
  'goalForm.typeOkr': 'OKR',
  'goalForm.quarter': 'Period (e.g. 2026-Q1)',
  'goalForm.targetDate': 'Due date',
  'goalForm.status': 'Status',
  'goalForm.progress': 'Progress: {value}%',
  'goalForm.err.titleRequired': 'Goal title is required.',
  'goalForm.err.employeeRequired': 'Select an employee.',
  'goalForm.saveNew': 'Add goal',
  'goalForm.saveEdit': 'Save changes',
  'goalForm.saving': 'Saving…',

  // Review form
  'reviewForm.title.new': 'New performance review',
  'reviewForm.title.edit': 'Edit review',
  'reviewForm.employee': 'Employee *',
  'reviewForm.period': 'Period (e.g. 2026-Q1, 2026-H1)',
  'reviewForm.type': 'Review type',
  'reviewForm.typePeriodic': 'Periodic review',
  'reviewForm.typeOkr': 'OKR review',
  'reviewForm.typeAnnual': 'Annual review',
  'reviewForm.managerRating': 'Manager rating (1-5)',
  'reviewForm.selfRating': 'Employee self-assessment (1-5)',
  'reviewForm.managerFeedback': 'Manager feedback',
  'reviewForm.managerFeedbackPh': 'Strengths, areas for improvement…',
  'reviewForm.selfAssessment': 'Employee self-assessment',
  'reviewForm.selfAssessmentPh': 'Employee reflection on their work…',
  'reviewForm.reviewedBy': 'Reviewer (email)',
  'reviewForm.status': 'Status',
  'reviewForm.err.employeeRequired': 'Select an employee.',
  'reviewForm.saveNew': 'Add review',
  'reviewForm.saveEdit': 'Save changes',
  'reviewForm.saving': 'Saving…',

  // Reports page
  'reports.employees': 'Employees',
  'reports.departments': 'Departments',
  'reports.positions': 'Positions',
  'reports.vacancies': 'Vacancies',
  'reports.empPerPion': 'Headcount by division',
  'reports.empPerPionSub': 'Employees per directorate (with sub-departments)',
  'reports.empPerPionStats': '{emp} emp. · {dept} depts',
  'reports.empPerLocation': 'Employees by location',
  'reports.empPerLocationSub': 'Geographic distribution',
  'reports.empCount': '{count} emp.',
  'reports.statusBreakdown': 'Employment status',
  'reports.statusActive': 'Active',
  'reports.statusOnLeave': 'On leave',
  'reports.statusTerminated': 'Terminated',
  'reports.positionStructure': 'Position structure',
  'reports.positionStructureSub': 'Level distribution',
  'reports.tenure': 'Tenure',
  'reports.tenureSub': 'Tenure distribution',
  'reports.tenure.lt1': '<1 year',
  'reports.tenure.1to3': '1-3 years',
  'reports.tenure.3to5': '3-5 years',
  'reports.tenure.5to10': '5-10 years',
  'reports.tenure.10plus': '10+ years',
  'reports.topCompetencies': 'Top competencies',
  'reports.topCompetenciesSub': 'Top 8 in company',
  'reports.openVacancies': 'Open vacancies',
  'reports.openVacanciesSub': '{count} unfilled positions',
  'reports.noVacancies': 'No open vacancies.',
  'reports.directory': 'Employee directory',
  'reports.directorySub': 'Full employee list',
  'reports.unknownLevel': 'Unspecified',
  'reports.donutLabel': 'employees',

  // Admin page
  'admin.title': 'Administration & security',
  'admin.subtitle': 'User roles, access control and change history',
  'admin.roles': 'Roles',
  'admin.accessRules': 'Access rules',
  'admin.historyEvents': 'History events',
  'admin.rolesTitle': 'User roles',
  'admin.rolesSub': 'Access profiles in the system',
  'admin.matrixTitle': 'Access control matrix',
  'admin.matrixSub': 'Read/write/delete permissions for each role and resource',
  'admin.resource': 'Resource',
  'admin.permRead': 'Read',
  'admin.permWrite': 'Write',
  'admin.permDelete': 'Delete',
  'admin.allowed': 'Allowed',
  'admin.denied': 'Denied',
  'admin.historyTitle': 'Change history',
  'admin.historySub': 'Audit log of recent system modifications',
  'admin.noHistory': 'No recorded changes.',
  'admin.resource.company': 'Company',
  'admin.resource.employees': 'Employees',
  'admin.resource.documents': 'Documents',
  'admin.resource.processes': 'Processes',
  'admin.resource.reports': 'Reports',
  'admin.resource.admin': 'Administration',

  // PDF export header
  'pdf.organigram': 'Organigram',
  'pdf.generated': 'Generated',
};

// Register all dictionaries here. To add a language, add its dict to this map.
const dictionaries: Record<Lang, Dict> = { pl, en };
